//! Common types for protobufs used by steam-wire.
//!
//! The protobuf surface is generated and consumed with [`prost`]: every message
//! is a plain prost struct, and the traits here adapt prost's `encode`/`decode`
//! to the `Read`/`Write` wire helpers the steam-wire transport layer speaks.

pub use bytes;
pub use prost;

use prost::Message;
use std::fmt::Debug;
use std::io::{Read, Write};

/// Constant used to verify that every proto crate is generated with the same
/// version of the codegen ([`steam-wire-proto-build`]).
///
/// A proto crate generated by a different codegen version references a different
/// `VERSION_*` symbol and therefore fails to compile against this crate — a
/// deliberate fail-fast that catches a stale/mismatched generated crate (for
/// example a rust-protobuf-era game crate) at build time instead of with
/// confusing trait errors deep in the graph.
///
/// [`steam-wire-proto-build`]: https://docs.rs/steam-wire-proto-build
pub const VERSION_0_6_0: () = ();

/// Error produced while encoding or decoding a protobuf [`RpcMessage`].
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum ProtoError {
    /// IO error reading from / writing to the underlying stream.
    #[error("io error while (de)serializing protobuf: {0}")]
    Io(#[from] std::io::Error),
    /// The bytes on the wire were not a valid protobuf message.
    #[error("failed to decode protobuf message: {0}")]
    Decode(#[from] prost::DecodeError),
}

pub trait RpcService {
    const SERVICE_NAME: &'static str;
}

/// A protobuf message for an rpc method with associated response
pub trait RpcMethod: Message + Default + RpcMessage {
    const METHOD_NAME: &'static str;
    type Response: RpcMessage;
}

/// A protobuf message sent as either request or response.
///
/// Blanket-implemented for every [`prost::Message`], so all generated message
/// structs satisfy it without any per-type generated code.
pub trait RpcMessage: Debug + Sized {
    fn parse(reader: &mut dyn Read) -> Result<Self, ProtoError>;

    fn write(&self, writer: &mut dyn Write) -> Result<(), ProtoError>;

    fn encode_size(&self) -> usize;
}

impl<T: Message + Default> RpcMessage for T {
    fn parse(reader: &mut dyn Read) -> Result<Self, ProtoError> {
        let mut buf = Vec::new();
        reader.read_to_end(&mut buf)?;
        Ok(T::decode(buf.as_slice())?)
    }

    fn write(&self, writer: &mut dyn Write) -> Result<(), ProtoError> {
        writer.write_all(&self.encode_to_vec())?;
        Ok(())
    }

    fn encode_size(&self) -> usize {
        self.encoded_len()
    }
}

/// An rpc message with associated kind.
///
/// The associated kind is used to differentiate incoming messages
pub trait RpcMessageWithKind: RpcMessage {
    type KindEnum: MsgKindEnum;
    const KIND: Self::KindEnum;
}

/// A generic wrapper for "kind" constants used by network messages
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub struct MsgKind(pub i32);

impl MsgKind {
    pub fn value(&self) -> i32 {
        self.0
    }
}

impl From<MsgKind> for i32 {
    fn from(value: MsgKind) -> Self {
        value.0
    }
}

pub const PROTO_MASK: u32 = 0x80000000;

/// An enum containing "kind" constants used by the network messages
///
/// Though it is possible to use the generic [`MsgKind`] struct. Applications shipping their own protobufs
/// are encouraged to create their own enums containing the constants in use for ease of use.
///
/// Implemented by the codegen for every generated `EMsg`-style enum (prost
/// enums are plain `#[repr(i32)]` C-like enums, so `*self as i32` yields the
/// wire value).
pub trait MsgKindEnum: Copy + Debug + Send + Sync + 'static {
    fn enum_value(&self) -> i32;

    fn encode_kind(&self, is_protobuf: bool) -> u32 {
        if is_protobuf {
            self.enum_value() as u32 | PROTO_MASK
        } else {
            self.enum_value() as u32
        }
    }
}

impl<T: MsgKindEnum> From<T> for MsgKind {
    fn from(value: T) -> Self {
        MsgKind(value.enum_value())
    }
}

impl<T: MsgKindEnum> PartialEq<T> for MsgKind {
    fn eq(&self, other: &T) -> bool {
        self.0.eq(&other.enum_value())
    }
}

/// Trait for implementing a check for completion of a job that returns a response stream
pub trait JobMultiple {
    /// If the job has completed
    fn completed(&self) -> bool;
}

/// Trait for game-specific game-coordinator handshakes
pub trait GCHandshake {
    /// The type of message send to the game-coordinator during handshake
    type Hello: RpcMessageWithKind + Send;

    /// The expected response type from the game-coordinator to our hello
    type Welcome: RpcMessageWithKind + Send;

    /// The steam app id we're getting the game-coordinator for
    fn app_id(&self) -> u32;

    /// An instance of the hello message to send
    fn hello(&self) -> Self::Hello;
}
