//! Codegen for the steam-wire protobuf crates.
//!
//! The pipeline is pure Rust (no `protoc`, no C toolchain):
//!
//! 1. [`protox`] parses the `.proto` surface into a [`FileDescriptorSet`].
//! 2. [`prost_build`] turns that descriptor set into plain prost structs/enums,
//!    written to a single flat module (the Steam protos have no `package`, so
//!    prost emits everything into one `_.rs`).
//! 3. We walk the same descriptor set to emit the steam-wire glue —
//!    [`RpcService`]/[`RpcMethod`]/[`RpcMessageWithKind`]/[`MsgKindEnum`] impls —
//!    and append it to that module.
//!
//! Every emitted ident is verified against the actual prost output (parsed with
//! [`syn`]) so a naming drift fails the build loudly instead of producing a
//! mismatched impl.
//!
//! [`RpcService`]: steam_wire_proto_common::RpcService
//! [`RpcMethod`]: steam_wire_proto_common::RpcMethod
//! [`RpcMessageWithKind`]: steam_wire_proto_common::RpcMessageWithKind
//! [`MsgKindEnum`]: steam_wire_proto_common::MsgKindEnum

mod kinds;

use heck::ToUpperCamelCase;
use kinds::{get_kinds, Kind};
use proc_macro2::{Ident, Span, TokenStream};
use prost_types::FileDescriptorSet;
use quote::quote;
use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

fn get_protos(path: impl AsRef<Path>) -> impl Iterator<Item = PathBuf> {
    WalkDir::new(path)
        .into_iter()
        .map(|res| res.expect("failed to read entry"))
        .filter(|entry| entry.path().is_file())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .and_then(|ext| ext.to_str())
                == Some("proto")
        })
        .filter(|entry| {
            !entry
                .file_name()
                .to_str()
                .expect("invalid filename")
                .starts_with('.')
        })
        .map(|entry| entry.into_path())
}

#[derive(clap::Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Folder containing the proto buffers
    protos: PathBuf,
    /// Target directory
    target: PathBuf,
}

fn main() {
    use clap::Parser;
    let args: Args = Args::parse();
    let mut protos = get_protos(&args.protos).collect::<Vec<_>>();
    protos.sort();

    // Clean up old generated files before generating new ones.
    if args.target.exists() {
        for entry in WalkDir::new(&args.target)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_file())
            .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("rs"))
        {
            std::fs::remove_file(entry.path()).unwrap_or_else(|e| {
                panic!("Failed to remove old generated file {:?}: {}", entry.path(), e)
            });
        }
    }

    // 1. Parse the protos with protox (pure Rust, no protoc).
    let fds = protox::compile(&protos, [&args.protos])
        .unwrap_or_else(|e| panic!("protox failed to parse the proto surface: {e}"));

    // 2. Extract the network-message kinds from the descriptor set.
    let kinds = get_kinds(&fds);

    // 3. Generate the prost types into a scratch dir, then read the single flat
    //    module back. `compile_fds` works straight off the descriptor set, so it
    //    does not shell out to protoc either.
    let scratch = std::env::temp_dir().join(format!("steam-wire-prost-{}", std::process::id()));
    std::fs::create_dir_all(&scratch).expect("failed to create scratch dir");
    let mut config = prost_build::Config::new();
    config.out_dir(&scratch);
    // zero-copy `bytes` fields, mirroring rust-protobuf's `with-bytes`.
    config.bytes(["."]);
    config
        .compile_fds(fds.clone())
        .expect("prost-build codegen failed");

    // The Steam protos have no `package`, so prost writes everything to `_.rs`.
    let generated_path = scratch.join("_.rs");
    let generated = std::fs::read_to_string(&generated_path).unwrap_or_else(|e| {
        panic!(
            "prost did not produce the expected flat module at {:?}: {}",
            generated_path, e
        )
    });

    // Index the generated symbols so every ident we emit can be verified.
    let symbols = Symbols::parse(&generated);

    // 4. Generate the steam-wire glue and verify it against `symbols`.
    let glue = generate_glue(&fds, &kinds, &symbols);
    let glue = prettyplease::unparse(
        &syn::parse2(glue).expect("generated glue should be valid Rust"),
    );

    let version_check = format!(
        "const _VENT_PROTO_VERSION_CHECK: () = ::steam_wire_proto_common::VERSION_{};",
        env!("CARGO_PKG_VERSION").replace('.', "_")
    );

    // The generated module is large machine output; silence lints for it.
    let header = "\
// @generated by steam-wire-proto-build (protox + prost-build). DO NOT EDIT.
#![allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]
#![allow(rustdoc::all, unused_imports, non_camel_case_types, non_snake_case)]
";

    let out = format!("{header}\n{generated}\n{version_check}\n\n{glue}\n");

    std::fs::create_dir_all(&args.target).expect("failed to create target dir");
    std::fs::write(args.target.join("mod.rs"), out).expect("failed to write generated module");

    let _ = std::fs::remove_dir_all(&scratch);
}

/// The structs and enums (with their variants) emitted by prost, used to verify
/// every ident we generate actually exists.
struct Symbols {
    structs: HashSet<String>,
    enums: HashMap<String, HashSet<String>>,
}

impl Symbols {
    fn parse(src: &str) -> Self {
        let file = syn::parse_file(src).expect("generated flat module should parse");
        let mut structs = HashSet::new();
        let mut enums = HashMap::new();
        // The kind enums and the network-message structs are all top-level in the
        // flat module (only nested messages/oneofs live in submodules, and those
        // are never RPC roots or kinds), so a shallow walk is sufficient.
        for item in &file.items {
            match item {
                syn::Item::Struct(s) => {
                    structs.insert(s.ident.to_string());
                }
                syn::Item::Enum(e) => {
                    enums.insert(
                        e.ident.to_string(),
                        e.variants.iter().map(|v| v.ident.to_string()).collect(),
                    );
                }
                _ => {}
            }
        }
        Symbols { structs, enums }
    }

    fn has_struct(&self, name: &str) -> bool {
        self.structs.contains(name)
    }

    fn has_enum(&self, name: &str) -> bool {
        self.enums.contains_key(name)
    }

    fn has_variant(&self, enum_name: &str, variant: &str) -> bool {
        self.enums
            .get(enum_name)
            .is_some_and(|variants| variants.contains(variant))
    }
}

/// prost's `to_upper_camel`: heck's `to_upper_camel_case` plus the `Self`
/// keyword guard. Used to predict prost's message/enum idents.
pub(crate) fn to_upper_camel(s: &str) -> String {
    let mut ident = s.to_upper_camel_case();
    if ident == "Self" {
        ident.push('_');
    }
    ident
}

/// prost's `strip_enum_prefix`: drop the enum-name prefix from a variant unless
/// doing so would leave an empty ident or one starting with a digit.
fn strip_enum_prefix(prefix: &str, name: &str) -> String {
    let stripped = name.strip_prefix(prefix).unwrap_or(name);
    match stripped.chars().next() {
        Some(c) if c.is_ascii_digit() => name.to_string(),
        Some(_) => stripped.to_string(),
        None => name.to_string(),
    }
}

/// Predict the prost variant ident for an enum value, matching prost-build's
/// `append_enum` exactly (`strip_enum_prefix(to_upper_camel(enum), to_upper_camel(value))`).
pub(crate) fn prost_enum_variant(enum_name: &str, variant_name: &str) -> String {
    strip_enum_prefix(&to_upper_camel(enum_name), &to_upper_camel(variant_name))
}

/// Map a proto type reference (e.g. `.CFoo_Bar_Request`) to its prost ident.
fn rust_type_from_proto_ref(reference: &str) -> String {
    let name = reference.rsplit('.').next().unwrap_or(reference);
    to_upper_camel(name)
}

/// Emit the steam-wire glue impls for the whole descriptor set, deterministically
/// ordered and verified against the generated `symbols`.
fn generate_glue(fds: &FileDescriptorSet, kinds: &[Kind], symbols: &Symbols) -> TokenStream {
    // Keyed by ident so the output is byte-stable regardless of file order.
    let mut services: BTreeMap<String, TokenStream> = BTreeMap::new();
    let mut methods: BTreeMap<String, TokenStream> = BTreeMap::new();
    let mut message_kinds: BTreeMap<String, TokenStream> = BTreeMap::new();
    let mut kind_enums: BTreeMap<String, TokenStream> = BTreeMap::new();

    for file in &fds.file {
        let file_name = file.name();

        // RpcService + RpcMethod
        for service in &file.service {
            let service_name = service.name().to_string();
            let service_ident = Ident::new(&service_name, Span::call_site());
            services.entry(service_name.clone()).or_insert_with(|| {
                quote! {
                    pub struct #service_ident {}

                    impl ::steam_wire_proto_common::RpcService for #service_ident {
                        const SERVICE_NAME: &'static str = #service_name;
                    }
                }
            });

            for method in &service.method {
                let full_name = format!("{}.{}#1", service_name, method.name());
                let request = rust_type_from_proto_ref(method.input_type());
                let response = rust_type_from_proto_ref(method.output_type());
                if !symbols.has_struct(&request) {
                    panic!(
                        "RPC request type `{request}` (method {full_name}, {file_name}) \
                         is not a generated message"
                    );
                }
                if !symbols.has_struct(&response) {
                    panic!(
                        "RPC response type `{response}` (method {full_name}, {file_name}) \
                         is not a generated message"
                    );
                }
                let request_ident = Ident::new(&request, Span::call_site());
                let response_ident = Ident::new(&response, Span::call_site());
                methods.entry(request).or_insert_with(|| {
                    quote! {
                        impl ::steam_wire_proto_common::RpcMethod for #request_ident {
                            const METHOD_NAME: &'static str = #full_name;
                            type Response = #response_ident;
                        }
                    }
                });
            }
        }

        // RpcMessageWithKind for every top-level message that maps to a kind.
        for message in &file.message_type {
            let proto_name = message.name();
            let Some(kind) = kinds
                .iter()
                .find(|kind| kind.matches(proto_name, Some(file_name)))
                .or_else(|| kinds.iter().find(|kind| kind.matches(proto_name, None)))
            else {
                continue;
            };

            let message_ident_str = to_upper_camel(proto_name);
            if !symbols.has_struct(&message_ident_str) {
                panic!("message `{proto_name}` -> `{message_ident_str}` is not generated");
            }
            if !symbols.has_variant(kind.enum_ident_str(), kind.variant_ident_str()) {
                panic!(
                    "kind variant `{}::{}` (proto `{}`) is not present in the generated enum",
                    kind.enum_ident_str(),
                    kind.variant_ident_str(),
                    kind.variant_proto(),
                );
            }

            let message_ident = Ident::new(&message_ident_str, Span::call_site());
            let kind_ident = kind.ident();
            let enum_ident = kind.enum_ident();
            message_kinds.entry(message_ident_str).or_insert_with(|| {
                quote! {
                    impl ::steam_wire_proto_common::RpcMessageWithKind for #message_ident {
                        type KindEnum = #enum_ident;
                        const KIND: Self::KindEnum = #kind_ident;
                    }
                }
            });
        }

        // MsgKindEnum for every kind enum (prost enums are plain `#[repr(i32)]`,
        // so `*self as i32` yields the wire value).
        for enum_type in &file.enum_type {
            let name = enum_type.name();
            if !(name.starts_with('E') && (name.ends_with("Msg") || name.ends_with("Messages"))) {
                continue;
            }
            let enum_ident_str = to_upper_camel(name);
            if !symbols.has_enum(&enum_ident_str) {
                continue;
            }
            let enum_ident = Ident::new(&enum_ident_str, Span::call_site());
            kind_enums.entry(enum_ident_str).or_insert_with(|| {
                quote! {
                    impl ::steam_wire_proto_common::MsgKindEnum for #enum_ident {
                        fn enum_value(&self) -> i32 {
                            *self as i32
                        }
                    }
                }
            });
        }
    }

    let services = services.into_values();
    let methods = methods.into_values();
    let message_kinds = message_kinds.into_values();
    let kind_enums = kind_enums.into_values();

    quote! {
        #(#services)*
        #(#methods)*
        #(#message_kinds)*
        #(#kind_enums)*
    }
}
